name: CI/CD for React App

on:
  push:
    branches:
      - master  # Trigger on push to main branch
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # ✅ Fix: Update Cache Version
      - name: Cache Docker layers
        uses: actions/cache@v3  # ✅ Change from v2 to v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # ✅ Fix: Ensure Docker Login Works
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # ✅ Fix: Build Docker Image with Proper Tagging
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: cvemulapalli/react-app:latest, cvemulapalli/react-app:${{ github.sha }}

      - name: Logout from Docker Hub
        run: docker logout
